# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sudeep Salgia
full_name: Sudeep Salgia
email: sudeepsalgia4@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sudeepsalgia.github.io" # the base hostname & protocol for your site
github_username:  sudeepsalgia
# twitter_username: kalpeshk2011
linkedin_username: sudeepsalgia
# stackoverflow: 5080995/martianwars
include: ['_pages']
# footer-links-active:
#   stackoverflow: true

# Build settings
markdown: kramdown
# gems:
#   - jekyll-seo-tag